import { GoogleGenAI } from '@google/genai';
import prisma from '../config/prisma.js'; // Adjust paths based on your client instance position
import { getIO } from '../socket.js';

// Initialize the Google Gen AI client wrapper instance
// Ensure GEMINI_API_KEY is defined in your backend .env file
const ai = new GoogleGenAI({});

export const analyzeTaskSpecifications = async (req, res) => {
  try {
    const { taskId } = req.params;

    // 1. Extract the unique task card from the data layer
    const task = await prisma.task.findUnique({
      where: { id: taskId },
      include: { project: true }
    });

    if (!task) {
      return res.status(404).json({ success: false, message: 'Target task blueprint not found.' });
    }

    if (!task.description || task.description.trim() === '') {
      return res.status(400).json({ success: false, message: 'Task description specs empty. Cannot generate context summary.' });
    }

    // 2. Format a system engineering prompt instructions matrix
    const systemPrompt = `
      You are an expert software architect acting as a DevSync AI automated team agent.
      Analyze the following task and break down exactly how an engineer should implement it.
      
      Task Title: ${task.title}
      Task Description: ${task.description}
      Priority: ${task.priority}
      
      Provide a clean response containing 3 to 5 highly structured, clear, and actionable bullet points or step instructions. Do not use Markdown formatting symbols like asterisks or hashtags. Keep sentences technical and short.
    `;

    // 3. Request insights from the gemini-2.5-flash model
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: systemPrompt,
    });

    const generatedText = response.text || 'No architectural steps could be generated by the engine.';

    // 4. Save the generated AI technical specs directly into your task row
    // Note: Assuming your task table has a text field to record agent thoughts (e.g., aiAnalysis, description, or notes)
    // We update the description to append the structural checklist smoothly
    const updatedDescription = `${task.description}\n\n🤖 DevSync AI Implementation Roadmap:\n${generatedText}`;

    const updatedTask = await prisma.task.update({
      where: { id: taskId },
      data: { description: updatedDescription },
      include: { assignee: true }
    });

    // 5. Broadcast this architectural update via Socket.io so the card upgrades live on the board screen
    getIO().to(task.projectId).emit('task:updated', updatedTask);

    return res.status(200).json({
      success: true,
      message: 'DevSync AI agent optimization complete.',
      data: updatedTask
    });

  } catch (error) {
    console.error('AI Agent Pipeline Exception:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to process task items through the AI pipeline.',
      error: error.message
    });
  }
};